// export const bg_image = require('./bg-image.jpg') 
export const company_logo = require('./company-logo.svg').default
export const dash_icon = require('./ic-dashboard.svg').default
export const docs_icon = require('./ic-docs.svg').default
export const history_icon = require('./ic-history.svg').default
export const user_icon = require('./ic-user.svg').default
export const wallet_icon = require('./ic-wallet.svg').default
export const toggle_icon = require('./ic-toggle.svg').default
export const setting_icon = require('./ic-setting.svg').default
export const cmp_white_logo = require('./company-white-logo.svg').default
export const bell = require('./ic-bell.svg').default
export const profile = require('./profile.png')
export const dropdown_white = require('./ic-white-arrow.svg').default
export const search_icon = require('./ic-search.svg').default
export const cmp_white_icon = require('./ic-brand-white.svg').default
export const card1 = require('./graph-1.svg').default
export const card2 = require('./graph-2.svg').default
export const card3 = require('./graph-3.svg').default